### ISSUE TITLE
FATAL EXCEPTION: RxCachedThreadScheduler-1

### ISSUE THREAD

**Issue by DevDCorp** [NYTimes/Store#277] opened 2017-10-17 12:13 UTC
I have downloaded and run your demo from git by using following url
> [https://github.com/NYTimes/Store]

but  loadPosts() of this demo give following exception, so please help me , i got stuck in this exception.

com.nytimes.android.store.sample E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                                Process: com.nytimes.android.store.sample, PID: 2951
                                                                                io.reactivex.exceptions.UndeliverableException: java.lang.NoSuchMethodError: No static method com_nytimes_android_external_store3_base_impl_RealInternalStore$$Lambda$1_lambda$lazyCache$0(Lcom/nytimes/android/external/store3/base/impl/RealInternalStore;Ljava/lang/Object;)Lio/reactivex/MaybeSource; in class Lcom/nytimes/android/external/store3/base/impl/RealInternalStore; or its super classes (declaration of 'com.nytimes.android.external.store3.base.impl.RealInternalStore' appears in /data/app/com.nytimes.android.store.sample-2/base.apk)
                                                                                    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
                                                                                    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:64)
                                                                                    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.NoSuchMethodError: No static method com_nytimes_android_external_store3_base_impl_RealInternalStore$$Lambda$1_lambda$lazyCache$0(Lcom/nytimes/android/external/store3/base/impl/RealInternalStore;Ljava/lang/Object;)Lio/reactivex/MaybeSource; in class Lcom/nytimes/android/external/store3/base/impl/RealInternalStore; or its super classes (declaration of 'com.nytimes.android.external.store3.base.impl.RealInternalStore' appears in /data/app/com.nytimes.android.store.sample-2/base.apk)
                                                                                    at com.nytimes.android.external.store3.base.impl.RealInternalStore$$Lambda$1.call(Unknown Source)
                                                                                    at io.reactivex.internal.operators.maybe.MaybeDefer.subscribeActual(MaybeDefer.java:41)
                                                                                    at io.reactivex.Maybe.subscribe(Maybe.java:3730)
                                                                                    at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46)
                                                                                    at io.reactivex.Maybe.subscribe(Maybe.java:3730)
                                                                                    at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
                                                                                    at io.reactivex.Maybe.subscribe(Maybe.java:3730)
                                                                                    at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
                                                                                    at io.reactivex.Single.subscribe(Single.java:2700)
                                                                                    at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
                                                                                    at io.reactivex.Observable.subscribe(Observable.java:10901)
                                                                                    at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                                    at io.reactivex.Observable.subscribe(Observable.java:10901)
                                                                                    at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
                                                                                    at io.reactivex.Single.subscribe(Single.java:2700)
                                                                                    at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                                    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                                    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by DevDCorp** [comment] 2017-10-17 12:15
Following line give the exception:- 

  this.persistedStore
                .get(awwRequest)
                .flatMapObservable(this::sanitizeData)
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(this::showPosts, throwable ->
                        Log.e(StoreActivity.class.getSimpleName(), throwable.getMessage(),
                                throwable));

**Comment by DevDCorp** [comment] 2017-10-17 12:17
My android studio details:-

android studio version:- 2.3.3
gradel dependency:-   classpath 'com.android.tools.build:gradle:2.3.3'

**Comment by digitalbuddha** [comment] 2017-10-23 12:11
We need to fix the sample app, seems to be outdated, duplicate of #273

**Closed as completed by digitalbuddha** 2017-10-23 12:11 UTC
