### ISSUE TITLE
Calls to fetch() and get() do not throw network error

### ISSUE THREAD

**Issue by Raenar4k** [NYTimes/Store#192] opened 2017-05-03 17:43 UTC
When calling `.fetch()` and `.get()` without internet connection store will return `Observable.empty()`.
This was somewhat unexpected, as readme explains:
> Calls to both fetch() and get() emit one value and then call onCompleted() or throw an error.

I was expecting to either get results from the network or to get network error from Retrofit as in this case.

I assume this is intended?  (as there is function`OnErrorResumeWithEmpty`  used in real store implementation).
If so, it could help other developers if readme would explain this behavior. :slightly_smiling_face:

For now i just used `.switchIfEmpty()` operator to handle such cases.

**Comment by digitalbuddha** [comment] 2017-05-03 17:51
Which version of the Store are you using? I think this was fixed in `2.0.5-SNAPSHOT`  Could you kindly make a failing test of your issue?

**Comment by digitalbuddha** [comment] 2017-05-03 18:01
The following test passes in latest Develop/Snapshot
```java
public class NoNetworkTest {

    private static final RuntimeException EXCEPTION = new RuntimeException();
    private Store<Object, BarCode> store;

    @Before
    public void setUp()  {
        store = StoreBuilder.barcode()
                .fetcher(barcode -> Observable.error(EXCEPTION))
                .open();
    }

    @Test
    public void testNoNetwork() throws Exception {
        store.get(new BarCode("test","test"))
                .test()
                .awaitTerminalEvent()
                .assertError(EXCEPTION);
    }
}
```

**Comment by digitalbuddha** [comment] 2017-05-04 13:50
Top of the morning! Wanted to check again on what issue you are having.

**Comment by Raenar4k** [comment] 2017-05-04 15:45
Im using version `2.0.4`. 
(Tried to use `2.0.5-SNAPSHOT`, but got stuck with this issue for a while http://stackoverflow.com/q/37084912).

I've tried the `NoNetworkTest` and it passes in my project!

I will try to make a test of my issue, but it will take a while (leaving for a week).
Thanks for quick feedback!

**Comment by digitalbuddha** [comment] 2017-05-13 19:08
Were you able to reproduce your issue?

**Comment by digitalbuddha** [comment] 2017-05-15 03:29
Closing due to inactivity

**Closed as completed by digitalbuddha** 2017-05-15 03:29 UTC

**Comment by charbgr** [comment] 2017-05-16 10:42
We also have this error with Dex on 2.0.5-SNAPSHOT.

FYI we don't have Retrolambda.

**Comment by digitalbuddha** [comment] 2017-05-16 10:50
Pls submit sample project or failing test showing what is not working
correctly.

On May 16, 2017 1:42 PM, "Vasilis Charalampakis" <notifications@github.com>
wrote:

We also have this error with Dex on 2.0.5-SNAPSHOT

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/NYTimes/Store/issues/192#issuecomment-301744252>, or mute
the thread

**Comment by charbgr** [comment] 2017-05-16 10:58
We get the following error: 
```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
```
