### ISSUE TITLE
Distinguish the source of data that a Store feeds

### ISSUE THREAD

**Issue by pavlospt** [NYTimes/Store#226] opened 2017-06-08 12:42 UTC
So the other day we were discussing with @charbgr that it would be great to know where the data from a `Store`, is coming from. It can be quite helpful in specific UI updates when loading data, e.g.: let a user know that the data she/he sees are possibly outdated :)

We suggest of adding a wrapper class that could distinguish the source for the data it holds. 

This could be an `Enum` or an `IntDef` whatever you prefer most. 

Let us know what you think about it and whether you need us to start a PR or something to help if you like the idea :)

**Comment by digitalbuddha** [comment] 2017-06-08 12:47
I'm not sure this needs to be feature if store. You could always create your own Response object and set a field on it in your fetcher or persister.

**Comment by pavlospt** [comment] 2017-06-08 12:53
@digitalbuddha If this is included in Store it will be 100% that you will always know the source of data, instead of having to duplicate code in all your possible fetchers and persisters :)

**Comment by digitalbuddha** [comment] 2017-06-09 11:32
#227 also wants wrapping to emit state. Maybe we can take both requests up on the rx2 branch prior to first real release of it.

**Comment by digitalbuddha** [comment] 2017-07-05 22:00
close as dupe of #227

**Closed as completed** 2017-07-27 03:16 UTC
